services:
  _defaults:
    public: true

  prestashop.module.freedompay.form.type.freedompay_configuration:
    class: 'PrestaShop\Module\FreedomPay\Form\FreedomPayConfigurationFormType'
    parent: 'form.type.translatable.aware'
    public: true
    tags:
      - { name: form.type }

  prestashop.module.freedompay.form.freedompay_configuration_data_configuration:
    class: 'PrestaShop\Module\FreedomPay\Form\FreedomPayConfigurationDataConfiguration'
    arguments: [ '@prestashop.adapter.legacy.configuration' ]

  prestashop.module.freedompay.form.freedompay_configuration_form_data_provider:
    class: 'PrestaShop\Module\FreedomPay\Form\FreedomPayConfigurationFormDataProvider'
    arguments:
      - '@prestashop.module.freedompay.form.freedompay_configuration_data_configuration'

  prestashop.module.freedompay.form.freedompay_configuration_form_data_handler:
    class: 'PrestaShop\PrestaShop\Core\Form\Handler'
    arguments:
      - '@form.factory'
      - '@prestashop.core.hook.dispatcher'
      - '@prestashop.module.freedompay.form.freedompay_configuration_form_data_provider'
      - 'PrestaShop\Module\FreedomPay\Form\FreedomPayConfigurationFormType'
      - 'DemoConfiguration'
